gui:
  theme:
    activeBorderColor:
      - "#59C2FF"
      - bold
    inactiveBorderColor:
      - "#5A6378"
    searchingActiveBorderColor:
      - "#FFB454"
      - bold
    optionsTextColor:
      - "#95E6CB"
    selectedLineBgColor:
      - "#59C2FF"
    inactiveViewSelectedLineBgColor:
      - "#0D1017"
      - bold
    cherryPickedCommitFgColor:
      - "#0D1017"
    cherryPickedCommitBgColor:
      - "#FFB454"
    markedBaseCommitFgColor:
      - "#95E6CB"
    markedBaseCommitBgColor:
      - "#FFB454"
    unstagedChangesColor:
      - "#F07178"
    defaultFgColor:
      - "#BFBDB6"
